# Generated by Django 4.2.7 on 2023-12-09 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='email',
            new_name='user',
        ),
    ]
